development:
  # the jquery_sdk version you want to use, read up on it here:
  # https://transloadit.com/blog/2013/02/transloadit-javascript-plugin-and-jquery-1-9
  # defaults to latest
  # use "v1.0.0" if you need IE6 support (using jQuery < 1.9)
  jquery_sdk_version: 'latest'
  auth:
    key     : '813a6f80898e11e5bd0915b47882f48c'
    secret  : 'ccb432d7994b03faef25bc26aa618342f069e7ee' # this is optional, but highly recommended, https://transloadit.com/docs/authentication
    duration: 1800 # 30 minute validity period for signed upload forms
  templates:
    # template identified by template_id
    s3_store: '0a11f6508e2d11e593546f2c3a9fc2cc'
production:
  # the jquery_sdk version you want to use, read up on it here:
  # https://transloadit.com/blog/2013/02/transloadit-javascript-plugin-and-jquery-1-9
  # defaults to latest
  # use "v1.0.0" if you need IE6 support (using jQuery < 1.9)
  jquery_sdk_version: 'latest'
  auth:
    key     : '813a6f80898e11e5bd0915b47882f48c'
    secret  : 'ccb432d7994b03faef25bc26aa618342f069e7ee' # this is optional, but highly recommended, https://transloadit.com/docs/authentication
    duration: 1800 # 30 minute validity period for signed upload forms

  templates:
    # template identified by template_id
    s3_store: 'S3_STORE_TEMPLATE_ID'

    # template defined inline
    image_resize:
      steps:
        resize:
          robot : '/image/resize'
          width : 320
          height: 200
